name: Merge Base Branch into PRs that have auto-merge enabled

on:
  pull_request:
    types:
      - opened
      - synchronize
      - auto_merge_enabled

jobs:
  merge_base_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Base Branch into PR
        uses: cycleapple/PR-Update@v1
        with:
          baseBranch: ${{ github.event.pull_request.base.ref }}
        if: ${{ github.event.pull_request.auto_merge }}
