on:
  push:

name: check
jobs:
  check:
    runs-on: [self-hosted]
    timeout-minutes: 15
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check package versions
        run: node common/scripts/install-run-rush.js change -v
      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install --no-link
      - name: Link dependencies
        run: node common/scripts/install-run-rush.js link
      - name: Build
        run: node common/scripts/install-run-rush.js rebuild --verbose
