on:
  push:

name: check
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [12.x]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install --no-link
      - name: Link dependencies
        run: node common/scripts/install-run-rush.js link
      - name: Build
        run: node common/scripts/install-run-rush.js rebuild --verbose
